name: CI

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Prepare logs dir
        run: mkdir -p logs

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          npm run build 2>&1 | tee logs/build.log

      - name: Upload production build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 7

      - name: Lint (non-blocking)
        shell: bash
        run: npm run lint 2>&1 | tee logs/lint.log
        continue-on-error: true

      - name: Typecheck (non-blocking)
        shell: bash
        run: npm run typecheck 2>&1 | tee logs/typecheck.log
        continue-on-error: true

      - name: Upload CI logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: logs
          retention-days: 7