name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backup_pre_friday-1/temp_zip_contents/project-bolt-sb1-mauveisk-3-friday/project/package-lock.json

      - name: Install dependencies
        working-directory: backup_pre_friday-1/temp_zip_contents/project-bolt-sb1-mauveisk-3-friday/project
        run: npm ci

      - name: Lint
        working-directory: backup_pre_friday-1/temp_zip_contents/project-bolt-sb1-mauveisk-3-friday/project
        run: npm run lint

      - name: Typecheck
        working-directory: backup_pre_friday-1/temp_zip_contents/project-bolt-sb1-mauveisk-3-friday/project
        run: npm run typecheck

      - name: Build
        working-directory: backup_pre_friday-1/temp_zip_contents/project-bolt-sb1-mauveisk-3-friday/project
        run: npm run build

      - name: Upload production build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: backup_pre_friday-1/temp_zip_contents/project-bolt-sb1-mauveisk-3-friday/project/dist