name: Secret Scan

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || 'HEAD~1' }}
          head: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'HEAD' }}

      - name: Summarize
        if: failure()
        run: |
          echo "Potential secrets detected by TruffleHog. Review the job logs and remediate."
